import { type Design, type InsertDesign, type InsertDesignV2 } from "@shared/schema";
import fs from "fs/promises";
import path from "path";
import { fileURLToPath } from "url";
import { db } from '../../db';
import { assets as assetsTable } from '@shared/schema';
import * as assetStore from './assetStore';

export interface IStorage {
  createDesign(design: InsertDesign | InsertDesignV2): Promise<Design>;
  getDesigns(limit?: number): Promise<Design[]>;
}

function normalizeV2ToLegacy(input: InsertDesignV2): InsertDesign & { version?: any } {
  const defaultPos = { x: 150, y: 150 };
  const front = (input.version?.sides || []).find((s: any) => s.name === 'front') || (input.version?.sides && input.version.sides[0]) || null;
  let slogan: any = null;
  let textSize = 24;
  let textRotation = 0;
  let textPosition: any = { x: 150, y: 135 };
  let image: any = undefined;
  let imageScale = 100;
  let imageRotation = 0;
  let imagePosition: any = defaultPos;

  if (front && Array.isArray(front.layers)) {
    const textLayer = front.layers.find((l: any) => l.type === 'text');
    const imageLayer = front.layers.find((l: any) => l.type === 'image');
    if (textLayer) {
      slogan = textLayer.text ?? '';
      textSize = textLayer.size ?? textSize;
      textRotation = textLayer.rotation ?? textRotation;
      if (textLayer.position) textPosition = textLayer.position;
    }
    if (imageLayer) {
      image = imageLayer.asset?.dataUrl ?? undefined;
      imageScale = typeof imageLayer.scale === 'number' ? Math.round(imageLayer.scale * 100) : imageScale;
      imageRotation = imageLayer.rotation ?? imageRotation;
      if (imageLayer.position) imagePosition = imageLayer.position;
    }
  }

  // Support explicit preview images generated by the client: prefer these if present
  try {
    const meta = (input as any).version?.metadata || {};
    if (meta?.preview_front) {
      image = meta.preview_front;
    }
  } catch (e) {
    // ignore
  }

  const legacy: any = {
    slogan,
    color: (input.templateColor as any) || '#ffffff',
    textSize,
    textRotation,
    textPosition,
    image,
    imageScale,
    imageRotation,
    imagePosition,
    product: input.product || 'T-shirt',
    template: input.template || 'tshirt',
    templateColor: input.templateColor || '#ffffff',
    // keep original v2 payload for future migration/inspection
    version: input.version,
  };

  // Support preview_back -> back_image mapping
  try {
    const meta = (input as any).version?.metadata || {};
    if (meta?.preview_back) {
      legacy.back_image = meta.preview_back;
    }
  } catch (e) {
    // ignore
  }

  return legacy as InsertDesign & { version?: any };
}

const __dirname = path.dirname(fileURLToPath(import.meta.url));

export class JsonStorage implements IStorage {
  private filePath = path.join(__dirname, "../../designs.json");

  private cache: { data: Design[]; ts: number } | null = null;
  private CACHE_TTL_MS = 2500; // small TTL for dev responsiveness

  private async readData(): Promise<Design[]> {
    const now = Date.now();
    if (this.cache && (now - this.cache.ts) < this.CACHE_TTL_MS) {
      return this.cache.data;
    }

    try {
      const data = await fs.readFile(this.filePath, "utf-8");
      try {
        const parsed = JSON.parse(data);
        const mapped = parsed.map((d: any) => ({ ...d, createdAt: new Date(d.createdAt) }));
        this.cache = { data: mapped, ts: now };
        return mapped;
      } catch (parseErr) {
        const corruptPath = `${this.filePath}.corrupt-${Date.now()}`;
        console.error("Storage: corrupted JSON detected, backing up to", corruptPath);
        await fs.rename(this.filePath, corruptPath);
        await fs.writeFile(this.filePath, "[]");
        this.cache = { data: [], ts: now };
        return [];
      }
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === "ENOENT") {
        this.cache = { data: [], ts: now };
        return [];
      }
      throw error;
    }
  }

  private async writeData(designs: Design[]) {
    const tmpPath = `${this.filePath}.tmp`;
    await fs.writeFile(tmpPath, JSON.stringify(designs, null, 2));
    await fs.rename(tmpPath, this.filePath);
    // Update cache immediately to avoid read-after-write file hits
    this.cache = { data: designs, ts: Date.now() };
  }

  async createDesign(insertDesign: InsertDesign | InsertDesignV2): Promise<Design> {
    const designs = await this.readData();
    let toStore: any = insertDesign;
    // Detect v2 payload and normalize into legacy fields while preserving v2 JSON
    if ((insertDesign as any).version) {
      toStore = normalizeV2ToLegacy(insertDesign as InsertDesignV2);
    }

    const newDesign: Design = {
      ...toStore,
      product: (toStore as any).product || "T-shirt",
      template: (toStore as any).template || "tshirt",
      templateColor: (toStore as any).templateColor || "#ffffff",
      id: designs.length + 1,
      createdAt: new Date(),
    } as Design;
    // If the client provided inline preview data URLs, persist them as PNG files
    const writePreviewIfDataUrl = async (dataUrl: any, suffix: string) => {
      if (!dataUrl || typeof dataUrl !== 'string') return null;
      if (!dataUrl.startsWith('data:')) return null;
      const m = dataUrl.match(/^data:(image\/png|image\/jpeg|image\/webp);base64,(.+)$/);
      if (!m) return null;
      const mime = m[1];
      const b64 = m[2];
      const ext = mime === 'image/png' ? 'png' : (mime === 'image/jpeg' ? 'jpg' : 'png');
      const filename = `design-${newDesign.id}-${suffix}.${ext}`;
      const outDir = path.join(__dirname, '..', '..', '..', 'client', 'attached_assets');
      try {
        await fs.mkdir(outDir, { recursive: true });
        const outPath = path.join(outDir, filename);
        console.log('storage: writing preview file to', outPath);
        const buf = Buffer.from(b64, 'base64');
        await fs.writeFile(outPath, buf);
        console.log('storage: wrote preview file', outPath);
        // If DB is available, insert an asset row so supplier listing can find it
        try {
        if (db) {
            const storageKey = `client/attached_assets/${filename}`;
            const previewMeta = { preview: true, selected_colors: (insertDesign as any)?.version?.metadata?.selected_colors || null, featured_color: (insertDesign as any)?.version?.metadata?.featured_color || null };
            const res = await db.insert(assetsTable).values({ filename, mime, size: buf.length, storage_key: storageKey, metadata: previewMeta }).returning();
            console.log('storage: inserted asset row', res?.[0]?.id);
          }
        } catch (ee) {
          console.error('storage: failed to insert asset row', ee && (ee.stack || ee.message) ? (ee.stack || ee.message) : ee);
        }
        return filename;
      } catch (e) {
        console.error('Failed to write preview file', e && (e.stack || e.message) ? (e.stack || e.message) : e);
        return null;
      }
    };

    // push to list early so id is stable for filenames
    designs.push(newDesign);
    console.log('json.createDesign: stored design id=', newDesign.id, 'hasVersion=', !!(insertDesign as any).version);
    // Sanitize any inline data: URLs inside the `version` payload by storing them
    // via the asset store and replacing with an asset reference (prefer /api/assets/:id).
    async function replaceDataUrlsInObject(obj: any, idPrefix: string) {
      if (!obj || typeof obj !== 'object') return;
      if (Array.isArray(obj)) {
        for (let i = 0; i < obj.length; i++) {
          const v = obj[i];
          if (typeof v === 'string' && v.startsWith('data:')) {
            try {
              const res = await assetStore.storeDataUrl(v, `${idPrefix}-${i}`);
              if (res && (res as any).id) obj[i] = `/api/assets/${(res as any).id}`;
              else if (res && (res as any).filename) obj[i] = `/attached_assets/${res.filename}`;
            } catch (e) {
              // ignore store errors — leave original data URL if storing fails
            }
          } else if (typeof v === 'object') {
            await replaceDataUrlsInObject(v, `${idPrefix}-${i}`);
          }
        }
        return;
      }

      for (const k of Object.keys(obj)) {
        const v = obj[k];
        if (typeof v === 'string' && v.startsWith('data:')) {
          try {
            const res = await assetStore.storeDataUrl(v, `${idPrefix}-${k}`);
            if (res && (res as any).id) obj[k] = `/api/assets/${(res as any).id}`;
            else if (res && (res as any).filename) obj[k] = `/attached_assets/${res.filename}`;
          } catch (e) {
            // ignore
          }
        } else if (typeof v === 'object') {
          await replaceDataUrlsInObject(v, `${idPrefix}-${k}`);
        }
      }
    }

    try {
      if ((newDesign as any).version) {
        await replaceDataUrlsInObject((newDesign as any).version, `design-${newDesign.id}-version`);
      }
    } catch (e) {
      console.error('storage: failed to sanitize version images', e && (e.stack || e.message) ? (e.stack || e.message) : e);
    }
    // write previews (if provided) and update newDesign fields to reference filenames
    try {
      if (newDesign.image && typeof newDesign.image === 'string' && newDesign.image.startsWith('data:')) {
        const fname = await writePreviewIfDataUrl(newDesign.image, 'front');
        if (fname) newDesign.image = fname;
      }
      if ((newDesign as any).back_image && typeof (newDesign as any).back_image === 'string' && (newDesign as any).back_image.startsWith('data:')) {
        const fname = await writePreviewIfDataUrl((newDesign as any).back_image, 'back');
        if (fname) (newDesign as any).back_image = fname;
      }
    } catch (e) {
      // ignore preview write errors
    }

    await this.writeData(designs);

    // generate masks for any images (optional)
    try {
      const { generateMaskFromBase64 } = await import('./maskGenerator');
      let updated = false;
      const MAX_INLINE_IMAGE_BYTES = 300 * 1024; // 300KB
      if (newDesign.image && typeof newDesign.image === 'string' && newDesign.image.startsWith('data:')) {
        try {
          const sizeBytes = Buffer.byteLength(newDesign.image, 'utf8');
          if (sizeBytes <= MAX_INLINE_IMAGE_BYTES) {
            const r = await generateMaskFromBase64(newDesign.image, `design-${newDesign.id}-front`);
            if (r) {
              if (r.composite) newDesign.image = r.composite;
              (newDesign as any).image_mask = r.mask;
              updated = true;
            }
          } else {
            console.warn('Skipping mask generation for front image because it is too large');
          }
        } catch(e) {
          // ignore
        }
      }
      if ((newDesign as any).back_image && typeof (newDesign as any).back_image === 'string' && (newDesign as any).back_image.startsWith('data:')) {
        try {
          const sizeBytes = Buffer.byteLength((newDesign as any).back_image, 'utf8');
          if (sizeBytes <= MAX_INLINE_IMAGE_BYTES) {
            const r = await generateMaskFromBase64((newDesign as any).back_image, `design-${newDesign.id}-back`);
            if (r) {
              if (r.composite) (newDesign as any).back_image = r.composite;
              (newDesign as any).back_image_mask = r.mask;
              updated = true;
            }
          } else {
            console.warn('Skipping mask generation for back image because it is too large');
          }
        } catch(e) {
          // ignore
        }
      }
      if (updated) {
        // persist changes
        const idx = designs.findIndex(d => d.id === newDesign.id);
        if (idx !== -1) {
          designs[idx] = newDesign;
          await this.writeData(designs);
        }
      }
    } catch (e) {
      // ignore
    }

    return newDesign;
  }

  async getDesigns(limit?: number): Promise<Design[]> {
    const designs = await this.readData();
    if (typeof limit === "number") return designs.slice(0, limit);
    return designs;
  }

  async getDesign(id: number): Promise<Design | undefined> {
    const designs = await this.readData();
    return designs.find((d) => d.id === id);
  }

  async updateDesign(id: number, changes: Partial<InsertDesign>): Promise<Design | undefined> {
    const designs = await this.readData();
    const idx = designs.findIndex((d) => d.id === id);
    if (idx === -1) return undefined;
    const updated = { ...designs[idx], ...changes } as Design;
    // If inline previews provided as data URLs, persist them as files under client/attached_assets
    const writePreviewIfDataUrl = async (dataUrl: any, suffix: string) => {
      if (!dataUrl || typeof dataUrl !== 'string') return null;
      if (!dataUrl.startsWith('data:')) return null;
      const m = String(dataUrl).match(/^data:(image\/png|image\/jpeg|image\/webp);base64,(.+)$/);
      if (!m) return null;
      const mime = m[1];
      const b64 = m[2];
      const ext = mime === 'image/png' ? 'png' : (mime === 'image/jpeg' ? 'jpg' : 'png');
      const filename = `design-${id}-${suffix}.${ext}`;
      const outDir = path.join(__dirname, '..', '..', '..', 'client', 'attached_assets');
      try {
        await fs.mkdir(outDir, { recursive: true });
        const outPath = path.join(outDir, filename);
        console.log('storage:update: writing preview file to', outPath);
        const buf = Buffer.from(b64, 'base64');
        await fs.writeFile(outPath, buf);
        console.log('storage:update: wrote preview file', outPath);
        try {
          if (db) {
            const storageKey = `client/attached_assets/${filename}`;
            const previewMeta = { preview: true, selected_colors: (changes as any)?.version?.metadata?.selected_colors || null, featured_color: (changes as any)?.version?.metadata?.featured_color || null };
            const res = await db.insert(assetsTable).values({ filename, mime, size: buf.length, storage_key: storageKey, metadata: previewMeta }).returning();
            console.log('storage:update: inserted asset row', res?.[0]?.id);
          }
        } catch (ee) {
          console.error('storage:update: failed to insert asset row', ee && (ee.stack || ee.message) ? (ee.stack || ee.message) : ee);
        }
        return filename;
      } catch (e) {
        console.error('Failed to write preview file', e && (e.stack || e.message) ? (e.stack || e.message) : e);
        return null;
      }
    };

    try {
      if (changes.image && typeof changes.image === 'string' && changes.image.startsWith('data:')) {
        const fname = await writePreviewIfDataUrl(changes.image, 'front');
        if (fname) updated.image = fname as any;
        else updated.image = changes.image as any;
      }
      if ((changes as any).back_image && typeof (changes as any).back_image === 'string' && (changes as any).back_image.startsWith('data:')) {
        const fname = await writePreviewIfDataUrl((changes as any).back_image, 'back');
        if (fname) (updated as any).back_image = fname as any;
        else (updated as any).back_image = (changes as any).back_image as any;
      }
    } catch (e) {
      // ignore file write errors
    }

    // Sanitize inline data: URLs in version or other nested fields by storing them
    // via the asset store and replacing with asset references.
    async function replaceDataUrlsInObject_update(obj: any, idPrefix: string) {
      if (!obj || typeof obj !== 'object') return;
      if (Array.isArray(obj)) {
        for (let i = 0; i < obj.length; i++) {
          const v = obj[i];
          if (typeof v === 'string' && v.startsWith('data:')) {
            try {
              const res = await assetStore.storeDataUrl(v, `${idPrefix}-${i}`);
              if (res && (res as any).id) obj[i] = `/api/assets/${(res as any).id}`;
              else if (res && (res as any).filename) obj[i] = `/attached_assets/${res.filename}`;
            } catch (e) {
              // ignore
            }
          } else if (typeof v === 'object') {
            await replaceDataUrlsInObject_update(v, `${idPrefix}-${i}`);
          }
        }
        return;
      }
      for (const k of Object.keys(obj)) {
        const v = obj[k];
        if (typeof v === 'string' && v.startsWith('data:')) {
          try {
            const res = await assetStore.storeDataUrl(v, `${idPrefix}-${k}`);
            if (res && (res as any).id) obj[k] = `/api/assets/${(res as any).id}`;
            else if (res && (res as any).filename) obj[k] = `/attached_assets/${res.filename}`;
          } catch (e) {
            // ignore
          }
        } else if (typeof v === 'object') {
          await replaceDataUrlsInObject_update(v, `${idPrefix}-${k}`);
        }
      }
    }

    try {
      if ((updated as any).version) {
        await replaceDataUrlsInObject_update((updated as any).version, `design-${id}-version`);
      }
    } catch (e) {
      console.error('storage:update: failed to sanitize version images', e && (e.stack || e.message) ? (e.stack || e.message) : e);
    }

    designs[idx] = updated;
    await this.writeData(designs);

    // generate masks if image changed
    try {
      const { generateMaskFromBase64 } = await import('./maskGenerator');
      let changed = false;

      const MAX_INLINE_IMAGE_BYTES = 300 * 1024; // 300KB
      if (changes.image && typeof changes.image === 'string' && changes.image.startsWith('data:')) {
        try {
          const sizeBytes = Buffer.byteLength(changes.image, 'utf8');
          if (sizeBytes <= MAX_INLINE_IMAGE_BYTES) {
            const r = await generateMaskFromBase64(changes.image, `design-${id}-front`);
            if (r) {
              if (r.composite) updated.image = r.composite as any;
              (updated as any).image_mask = r.mask;
              changed = true;
            }
          } else {
            console.warn('Skipping mask generation for front image because it is too large');
          }
        } catch(e) {
          // ignore
        }
      }

      if ((changes as any).back_image && typeof (changes as any).back_image === 'string' && (changes as any).back_image.startsWith('data:')) {
        try {
          const sizeBytes = Buffer.byteLength((changes as any).back_image, 'utf8');
          if (sizeBytes <= MAX_INLINE_IMAGE_BYTES) {
            const r = await generateMaskFromBase64((changes as any).back_image, `design-${id}-back`);
            if (r) {
              if (r.composite) (updated as any).back_image = r.composite as any;
              (updated as any).back_image_mask = r.mask;
              changed = true;
            }
          } else {
            console.warn('Skipping mask generation for back image because it is too large');
          }
        } catch(e) {
          // ignore
        }
      }

      if (changed) {
        designs[idx] = updated;
        await this.writeData(designs);
      }
    } catch (e) {
      // ignore
    }

    return updated;
  }

  async deleteDesign(id: number): Promise<boolean> {
    const designs = await this.readData();
    const idx = designs.findIndex((d) => d.id === id);
    if (idx === -1) return false;
    designs.splice(idx, 1);
    await this.writeData(designs);
    return true;
  }
}

// Try DB implementation if available
let storageImpl: any;
let storageType: 'db' | 'json' = 'json';
try {
  // storage-db.ts is located at the repository server root; import relative to this file
  const { dbStorage } = await import("../../storage-db");
  const dbConfigured = !!(
    process.env.DATABASE_URL || process.env.DB_NAME || process.env.DB_USER || process.env.DB_PASSWORD
  );

  if (dbConfigured) {
    storageImpl = dbStorage;
    storageType = 'db';
    console.log('Using Postgres-backed storage');
  }
} catch (e) {
  // ignore import errors and fallback to JSON storage
}

if (!storageImpl) {
  storageImpl = new JsonStorage();
  storageType = 'json';
  console.log('Using JSON file storage');
}

export const storage = storageImpl;
export function getStorageType() {
  return storageType;
}
